### ISSUE TITLE
How do i set up in local environment?

### ISSUE THREAD

**Issue by KraXen72** [glomatico/gytmdl#14]
i installed it with `python install -r requirements.txt` with python 3.12.0
then running `python gytmdl` throws:
```
Traceback (most recent call last):
  File "D:\coding\python\gytmdl\gytmdl\cli.py", line 8, in <module>
    from . import __version__
ImportError: attempted relative import with no known parent package
```
and if i change the relative imports to `gytmdl.dl`, etc
```
Traceback (most recent call last):
  File "D:\coding\python\gytmdl\gytmdl\cli.py", line 8, in <module>
    from gytmdl import __version__
ModuleNotFoundError: No module named 'gytmdl
```

what is the correct way to set this up for development? can you please add a guide to the readme, for people who want to contribute? thanks.

**Comment by glomatico** [comment]
Go to the repo folder and run with `python -m gytmdl`
