### ISSUE TITLE
Download OPUS in OGG container (.opus)

### ISSUE THREAD

**Issue by tibequadorian** [glomatico/gytmdl#19]
Is there a reason why we save `-i 251` downloads as `.m4a` files?
Can you support saving in an OGG container, as done in yt-dlp with `-x -f 251` by default?

**Comment by glomatico** [comment]
Using mp4 container for all formats increases compatibility with some players and allows to have one code for tagging.

**Comment by tibequadorian** [comment]
okay I understand, feel free to close this issue.

**Comment by glomatico** [comment]
Okay!
