### ISSUE TITLE
Cannot load the program on python 3.13

### ISSUE THREAD

**Issue by 2019Z2** [glomatico/gytmdl#28]
> > Traceback (most recent call last):
> 
>   File "/home/solomon/.local/bin/gytmdl", line 5, in <module>
>     from gytmdl.cli import main
>   File "/home/solomon/.local/lib/python3.13/site-packages/gytmdl/cli.py", line 14, in <module>
>     from .downloader import Downloader
>   File "/home/solomon/.local/lib/python3.13/site-packages/gytmdl/downloader.py", line 15, in <module>
>     from mutagen.mp4 import MP4, MP4Cover
> ModuleNotFoundError: No module named 'mutagen'

**Comment by Veha0001** [comment]
Install the package bro..
```bash
pip install mutagen
```

**Comment by michaelrussell4** [comment]
```sh
(venv) C:\Users\...>uv pip install mutagen 
Resolved 1 package in 283ms
Prepared 1 package in 215ms
Installed 1 package in 85ms
 + mutagen==1.47.0

(venv) C:\Users\...>gytmdl "https://music.youtube.com/channel/UCwZEU0wAwIyZb4x5G_KJp2w"
[CRITICAL 10:56:00] FFmpeg not found at "ffmpeg"
```

**Comment by Veha0001** [comment]
> ```sh
> (venv) C:\Users\...>uv pip install mutagen 
> Resolved 1 package in 283ms
> Prepared 1 package in 215ms
> Installed 1 package in 85ms
>  + mutagen==1.47.0
> 
> (venv) C:\Users\...>gytmdl "https://music.youtube.com/channel/UCwZEU0wAwIyZb4x5G_KJp2w"
> [CRITICAL 10:56:00] FFmpeg not found at "ffmpeg"
> ```
> 
> Another error after installing mutagen. I'm using python=3.12.5

- For Windows:
```pwsh
winget install  Gyan.FFmpeg
```
> [!NOTE]
> I used to install `gytmdl` with (MSYS2)[https://www.msys2.org/] because there are some errors when installing it on Windows...zz
