### ISSUE TITLE
Downloads only the first 200 items of a playlist/album

### ISSUE THREAD

**Issue by chriszero** [glomatico/gytmdl#3]
If a playlist have more than 200 items, all items after the 200. item fails with a not very verbose "error".
Audiobooks have often over 200 items. 

`
Traceback (most recent call last):
  File "C:\Users\USER\gytmdl\gytmdl\Lib\site-packages\gytmdl\cli.py", line 240, in cli
    tags = dl.get_tags(ytmusic_watch_playlist)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\gytmdl\gytmdl\Lib\site-packages\gytmdl\dl.py", line 138, in get_tags
    if ytmusic_album["tracks"][i]["isExplicit"]:
       ~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
`

**Comment by chriszero** [comment]
The downloader runs fine if the index is checked before.
But why it happens only after item 200? To be investigated...

**Comment by glomatico** [comment]
It seems that YouTube Music API is only returning the first 200 songs of an album.

**Comment by chriszero** [comment]
#4
