### ISSUE TITLE
'type' object not subscriptable

### ISSUE THREAD

**Issue by ThexUniverse** [glomatico/gytmdl#5]
Upon installing the program via command line on windows and attempting to use the gytmdl command, it returns the "'type' object not subscriptable" error. I have also noticed that the ".gytmdl" folder was not created after attempting to run the command. I am using python 3.8.10.

**Comment by glomatico** [comment]
Try adding `-n` on the command line

**Comment by purnadika** [comment]
got the same issue. It's on win 7 starter 32bit with py 3.8.10
![image](https://github.com/glomatico/gytmdl/assets/9426610/f0cc240c-a5d0-47b1-8cd5-3c67e71a221a)
![image](https://github.com/glomatico/gytmdl/assets/9426610/7ad0d883-d171-4b5c-88f6-4c38494b818e)
